### ISSUE TITLE
I recently found that It shows error when I run the app

### ISSUE THREAD

**Issue by qiuwenqiao** [steven-michaud/HookCase#13]
Application Specific Information:
dyld: launch, running initializers

Thread 0 Crashed:
0   libdyld.dylib                 	0x00007fff62af5f10 dyld3::dyld_get_image_versions(mach_header const*, void (unsigned int, unsigned int, unsigned int) block_pointer) + 30
1   libdyld.dylib                 	0x00007fff62af6429 dyld_get_active_platform + 51
2   libdyld.dylib                 	0x00007fff62af6d64 dlopen + 233
3   dyld                          	0x000000010ec7e69e dyld::getExecutablePath() + 13
4   dyld                          	0x000000010ec7d503 dyldbootstrap::start(macho_header const*, int, char const**, long, macho_header const*, unsigned long*) + 1167
5   dyld                          	0x000000010ec7d036 _dyld_start + 54

**Comment by steven-michaud** [comment]
What was your hook library? Which application were you loading it into? What version of macOS were you running?

**Comment by qiuwenqiao** [comment]
Thank you for your replay. I found that the problem is the path of the dylib. When I put the dylib to /library/extensions, the app will crash. When I move the dylib to my desktop, It's OK. So I think It isn't the problem of hookcase. But I realy remember everything was OK a few days ago. My OS version is 10.14.6. and I found 10.14.5 has the save problem.

**Comment by steven-michaud** [comment]
I'm closing this because it doesn't report a bug in HookCase.

If by "the dylib" you mean your hook library, there's no reason to put it in /Library/Extensions. I usually use it from wherever I built it. As for the HookCase.kext kernel extension, it should go into a directory owned by root:wheel -- like /usr/local/sbin. /Library/Extensions is for extensions signed with special extension-only signing certificates, provided by Apple. Those will get loaded automatically when the computer (re)starts. But HookCase.kext won't load from /Library/Extensions, even if you sign it with your developer signing certificate (from Apple).
